apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: kiii-nginx
          image: stefantagarski/kiii-ngnix:2.0
          ports:
              - containerPort: 80

